// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: grpcachieve/api.proto

package grpcachieve

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetExpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetExpRequest) Reset() {
	*x = GetExpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcachieve_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpRequest) ProtoMessage() {}

func (x *GetExpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcachieve_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpRequest.ProtoReflect.Descriptor instead.
func (*GetExpRequest) Descriptor() ([]byte, []int) {
	return file_grpcachieve_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetExpRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetExpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Points int64  `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`
	Level  int64  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *GetExpResponse) Reset() {
	*x = GetExpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcachieve_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpResponse) ProtoMessage() {}

func (x *GetExpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcachieve_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpResponse.ProtoReflect.Descriptor instead.
func (*GetExpResponse) Descriptor() ([]byte, []int) {
	return file_grpcachieve_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetExpResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetExpResponse) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *GetExpResponse) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_grpcachieve_api_proto protoreflect.FileDescriptor

var file_grpcachieve_api_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x72, 0x70, 0x63, 0x61, 0x63, 0x68, 0x69, 0x65, 0x76, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x72, 0x70, 0x63, 0x61, 0x63, 0x68,
	0x69, 0x65, 0x76, 0x65, 0x22, 0x28, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x57,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x32, 0x59, 0x0a, 0x12, 0x41, 0x63, 0x68, 0x69, 0x65,
	0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x61, 0x63,
	0x68, 0x69, 0x65, 0x76, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x61, 0x63, 0x68, 0x69, 0x65, 0x76,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcachieve_api_proto_rawDescOnce sync.Once
	file_grpcachieve_api_proto_rawDescData = file_grpcachieve_api_proto_rawDesc
)

func file_grpcachieve_api_proto_rawDescGZIP() []byte {
	file_grpcachieve_api_proto_rawDescOnce.Do(func() {
		file_grpcachieve_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcachieve_api_proto_rawDescData)
	})
	return file_grpcachieve_api_proto_rawDescData
}

var file_grpcachieve_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcachieve_api_proto_goTypes = []interface{}{
	(*GetExpRequest)(nil),  // 0: grpcachieve.GetExpRequest
	(*GetExpResponse)(nil), // 1: grpcachieve.GetExpResponse
}
var file_grpcachieve_api_proto_depIdxs = []int32{
	0, // 0: grpcachieve.AchievementService.GetExp:input_type -> grpcachieve.GetExpRequest
	1, // 1: grpcachieve.AchievementService.GetExp:output_type -> grpcachieve.GetExpResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcachieve_api_proto_init() }
func file_grpcachieve_api_proto_init() {
	if File_grpcachieve_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcachieve_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcachieve_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcachieve_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcachieve_api_proto_goTypes,
		DependencyIndexes: file_grpcachieve_api_proto_depIdxs,
		MessageInfos:      file_grpcachieve_api_proto_msgTypes,
	}.Build()
	File_grpcachieve_api_proto = out.File
	file_grpcachieve_api_proto_rawDesc = nil
	file_grpcachieve_api_proto_goTypes = nil
	file_grpcachieve_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AchievementServiceClient is the client API for AchievementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AchievementServiceClient interface {
	GetExp(ctx context.Context, in *GetExpRequest, opts ...grpc.CallOption) (*GetExpResponse, error)
}

type achievementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAchievementServiceClient(cc grpc.ClientConnInterface) AchievementServiceClient {
	return &achievementServiceClient{cc}
}

func (c *achievementServiceClient) GetExp(ctx context.Context, in *GetExpRequest, opts ...grpc.CallOption) (*GetExpResponse, error) {
	out := new(GetExpResponse)
	err := c.cc.Invoke(ctx, "/grpcachieve.AchievementService/GetExp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AchievementServiceServer is the server API for AchievementService service.
type AchievementServiceServer interface {
	GetExp(context.Context, *GetExpRequest) (*GetExpResponse, error)
}

// UnimplementedAchievementServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAchievementServiceServer struct {
}

func (*UnimplementedAchievementServiceServer) GetExp(context.Context, *GetExpRequest) (*GetExpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExp not implemented")
}

func RegisterAchievementServiceServer(s *grpc.Server, srv AchievementServiceServer) {
	s.RegisterService(&_AchievementService_serviceDesc, srv)
}

func _AchievementService_GetExp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AchievementServiceServer).GetExp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcachieve.AchievementService/GetExp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AchievementServiceServer).GetExp(ctx, req.(*GetExpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AchievementService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcachieve.AchievementService",
	HandlerType: (*AchievementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExp",
			Handler:    _AchievementService_GetExp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcachieve/api.proto",
}
