// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.3
// source: mqbank/mqbank.proto

package mqbank

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CurrencyType int32

const (
	CurrencyType_UNKNOWN CurrencyType = 0
	CurrencyType_CHIPS   CurrencyType = 1
	CurrencyType_COINS   CurrencyType = 2
)

// Enum value maps for CurrencyType.
var (
	CurrencyType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CHIPS",
		2: "COINS",
	}
	CurrencyType_value = map[string]int32{
		"UNKNOWN": 0,
		"CHIPS":   1,
		"COINS":   2,
	}
)

func (x CurrencyType) Enum() *CurrencyType {
	p := new(CurrencyType)
	*p = x
	return p
}

func (x CurrencyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CurrencyType) Descriptor() protoreflect.EnumDescriptor {
	return file_mqbank_mqbank_proto_enumTypes[0].Descriptor()
}

func (CurrencyType) Type() protoreflect.EnumType {
	return &file_mqbank_mqbank_proto_enumTypes[0]
}

func (x CurrencyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CurrencyType.Descriptor instead.
func (CurrencyType) EnumDescriptor() ([]byte, []int) {
	return file_mqbank_mqbank_proto_rawDescGZIP(), []int{0}
}

type DepositRequest_Type int32

const (
	DepositRequest_UNKNOWN         DepositRequest_Type = 0
	DepositRequest_BONUS           DepositRequest_Type = 1
	DepositRequest_CASH_GAME       DepositRequest_Type = 2
	DepositRequest_NEW_LEVEL       DepositRequest_Type = 3
	DepositRequest_NEW_ACHIEVEMENT DepositRequest_Type = 4
	DepositRequest_ASSIGNMENT      DepositRequest_Type = 5
	DepositRequest_SURVIVAL        DepositRequest_Type = 6
)

// Enum value maps for DepositRequest_Type.
var (
	DepositRequest_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "BONUS",
		2: "CASH_GAME",
		3: "NEW_LEVEL",
		4: "NEW_ACHIEVEMENT",
		5: "ASSIGNMENT",
		6: "SURVIVAL",
	}
	DepositRequest_Type_value = map[string]int32{
		"UNKNOWN":         0,
		"BONUS":           1,
		"CASH_GAME":       2,
		"NEW_LEVEL":       3,
		"NEW_ACHIEVEMENT": 4,
		"ASSIGNMENT":      5,
		"SURVIVAL":        6,
	}
)

func (x DepositRequest_Type) Enum() *DepositRequest_Type {
	p := new(DepositRequest_Type)
	*p = x
	return p
}

func (x DepositRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DepositRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_mqbank_mqbank_proto_enumTypes[1].Descriptor()
}

func (DepositRequest_Type) Type() protoreflect.EnumType {
	return &file_mqbank_mqbank_proto_enumTypes[1]
}

func (x DepositRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DepositRequest_Type.Descriptor instead.
func (DepositRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_mqbank_mqbank_proto_rawDescGZIP(), []int{1, 0}
}

type BalanceUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OperationId string `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
}

func (x *BalanceUpdate) Reset() {
	*x = BalanceUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqbank_mqbank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceUpdate) ProtoMessage() {}

func (x *BalanceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_mqbank_mqbank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceUpdate.ProtoReflect.Descriptor instead.
func (*BalanceUpdate) Descriptor() ([]byte, []int) {
	return file_mqbank_mqbank_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceUpdate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BalanceUpdate) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type DepositRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated, use amount.
	Chips  int64 `protobuf:"varint,1,opt,name=chips,proto3" json:"chips,omitempty"`
	Amount int64 `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	// Deprecated, use reason.
	Type   DepositRequest_Type `protobuf:"varint,2,opt,name=type,proto3,enum=mqbank.DepositRequest_Type" json:"type,omitempty"`
	Reason string              `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Description string              `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// to whom make the deposit
	UserId       string       `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	CurrencyType CurrencyType `protobuf:"varint,6,opt,name=currencyType,proto3,enum=mqbank.CurrencyType" json:"currencyType,omitempty"`
}

func (x *DepositRequest) Reset() {
	*x = DepositRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqbank_mqbank_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest) ProtoMessage() {}

func (x *DepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mqbank_mqbank_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRequest.ProtoReflect.Descriptor instead.
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return file_mqbank_mqbank_proto_rawDescGZIP(), []int{1}
}

func (x *DepositRequest) GetChips() int64 {
	if x != nil {
		return x.Chips
	}
	return 0
}

func (x *DepositRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DepositRequest) GetType() DepositRequest_Type {
	if x != nil {
		return x.Type
	}
	return DepositRequest_UNKNOWN
}

func (x *DepositRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DepositRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DepositRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DepositRequest) GetCurrencyType() CurrencyType {
	if x != nil {
		return x.CurrencyType
	}
	return CurrencyType_UNKNOWN
}

type MultiDeposit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deposits []*UserDeposit `protobuf:"bytes,1,rep,name=deposits,proto3" json:"deposits,omitempty"`
	Service  string         `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *MultiDeposit) Reset() {
	*x = MultiDeposit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqbank_mqbank_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiDeposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiDeposit) ProtoMessage() {}

func (x *MultiDeposit) ProtoReflect() protoreflect.Message {
	mi := &file_mqbank_mqbank_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiDeposit.ProtoReflect.Descriptor instead.
func (*MultiDeposit) Descriptor() ([]byte, []int) {
	return file_mqbank_mqbank_proto_rawDescGZIP(), []int{2}
}

func (x *MultiDeposit) GetDeposits() []*UserDeposit {
	if x != nil {
		return x.Deposits
	}
	return nil
}

func (x *MultiDeposit) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type UserDeposit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount      int64  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	UserId      string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *UserDeposit) Reset() {
	*x = UserDeposit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqbank_mqbank_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDeposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeposit) ProtoMessage() {}

func (x *UserDeposit) ProtoReflect() protoreflect.Message {
	mi := &file_mqbank_mqbank_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeposit.ProtoReflect.Descriptor instead.
func (*UserDeposit) Descriptor() ([]byte, []int) {
	return file_mqbank_mqbank_proto_rawDescGZIP(), []int{3}
}

func (x *UserDeposit) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UserDeposit) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserDeposit) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_mqbank_mqbank_proto protoreflect.FileDescriptor

var file_mqbank_mqbank_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x71, 0x62, 0x61, 0x6e, 0x6b, 0x2f, 0x6d, 0x71, 0x62, 0x61, 0x6e, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x71, 0x62, 0x61, 0x6e, 0x6b, 0x22, 0x4b, 0x0a,
	0x0d, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0xec, 0x02, 0x0a, 0x0e, 0x44,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x68, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x68,
	0x69, 0x70, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6d, 0x71, 0x62, 0x61,
	0x6e, 0x6b, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x38,
	0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6d, 0x71, 0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x54, 0x79, 0x70, 0x65, 0x22, 0x6f, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x42, 0x4f, 0x4e, 0x55, 0x53, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x41, 0x53, 0x48,
	0x5f, 0x47, 0x41, 0x4d, 0x45, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x45, 0x57, 0x5f, 0x4c,
	0x45, 0x56, 0x45, 0x4c, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x4e, 0x45, 0x57, 0x5f, 0x41, 0x43,
	0x48, 0x49, 0x45, 0x56, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x41,
	0x53, 0x53, 0x49, 0x47, 0x4e, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x53,
	0x55, 0x52, 0x56, 0x49, 0x56, 0x41, 0x4c, 0x10, 0x06, 0x22, 0x59, 0x0a, 0x0c, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x12, 0x2f, 0x0a, 0x08, 0x64, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x71,
	0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x52, 0x08, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0x5f, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x31, 0x0a, 0x0c, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x48, 0x49, 0x50, 0x53, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x43, 0x4f, 0x49, 0x4e, 0x53, 0x10, 0x02, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mqbank_mqbank_proto_rawDescOnce sync.Once
	file_mqbank_mqbank_proto_rawDescData = file_mqbank_mqbank_proto_rawDesc
)

func file_mqbank_mqbank_proto_rawDescGZIP() []byte {
	file_mqbank_mqbank_proto_rawDescOnce.Do(func() {
		file_mqbank_mqbank_proto_rawDescData = protoimpl.X.CompressGZIP(file_mqbank_mqbank_proto_rawDescData)
	})
	return file_mqbank_mqbank_proto_rawDescData
}

var file_mqbank_mqbank_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mqbank_mqbank_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mqbank_mqbank_proto_goTypes = []interface{}{
	(CurrencyType)(0),        // 0: mqbank.CurrencyType
	(DepositRequest_Type)(0), // 1: mqbank.DepositRequest.Type
	(*BalanceUpdate)(nil),    // 2: mqbank.BalanceUpdate
	(*DepositRequest)(nil),   // 3: mqbank.DepositRequest
	(*MultiDeposit)(nil),     // 4: mqbank.MultiDeposit
	(*UserDeposit)(nil),      // 5: mqbank.UserDeposit
}
var file_mqbank_mqbank_proto_depIdxs = []int32{
	1, // 0: mqbank.DepositRequest.type:type_name -> mqbank.DepositRequest.Type
	0, // 1: mqbank.DepositRequest.currencyType:type_name -> mqbank.CurrencyType
	5, // 2: mqbank.MultiDeposit.deposits:type_name -> mqbank.UserDeposit
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mqbank_mqbank_proto_init() }
func file_mqbank_mqbank_proto_init() {
	if File_mqbank_mqbank_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mqbank_mqbank_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqbank_mqbank_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqbank_mqbank_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiDeposit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqbank_mqbank_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDeposit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mqbank_mqbank_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mqbank_mqbank_proto_goTypes,
		DependencyIndexes: file_mqbank_mqbank_proto_depIdxs,
		EnumInfos:         file_mqbank_mqbank_proto_enumTypes,
		MessageInfos:      file_mqbank_mqbank_proto_msgTypes,
	}.Build()
	File_mqbank_mqbank_proto = out.File
	file_mqbank_mqbank_proto_rawDesc = nil
	file_mqbank_mqbank_proto_goTypes = nil
	file_mqbank_mqbank_proto_depIdxs = nil
}
