// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: mqmarket/api.proto

package mqmarket

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Gift_TimeFrame int32

const (
	Gift_UNKNOWN Gift_TimeFrame = 0
	Gift_DAY     Gift_TimeFrame = 1
	Gift_WEEK    Gift_TimeFrame = 2
	Gift_MONTH   Gift_TimeFrame = 3
)

// Enum value maps for Gift_TimeFrame.
var (
	Gift_TimeFrame_name = map[int32]string{
		0: "UNKNOWN",
		1: "DAY",
		2: "WEEK",
		3: "MONTH",
	}
	Gift_TimeFrame_value = map[string]int32{
		"UNKNOWN": 0,
		"DAY":     1,
		"WEEK":    2,
		"MONTH":   3,
	}
)

func (x Gift_TimeFrame) Enum() *Gift_TimeFrame {
	p := new(Gift_TimeFrame)
	*p = x
	return p
}

func (x Gift_TimeFrame) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gift_TimeFrame) Descriptor() protoreflect.EnumDescriptor {
	return file_mqmarket_api_proto_enumTypes[0].Descriptor()
}

func (Gift_TimeFrame) Type() protoreflect.EnumType {
	return &file_mqmarket_api_proto_enumTypes[0]
}

func (x Gift_TimeFrame) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gift_TimeFrame.Descriptor instead.
func (Gift_TimeFrame) EnumDescriptor() ([]byte, []int) {
	return file_mqmarket_api_proto_rawDescGZIP(), []int{0, 0}
}

type Gift struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToUserId  string         `protobuf:"bytes,1,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	ItemId    string         `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Units     int64          `protobuf:"varint,3,opt,name=units,proto3" json:"units,omitempty"`
	TimeFrame Gift_TimeFrame `protobuf:"varint,4,opt,name=time_frame,json=timeFrame,proto3,enum=mqmarket.Gift_TimeFrame" json:"time_frame,omitempty"`
}

func (x *Gift) Reset() {
	*x = Gift{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqmarket_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gift) ProtoMessage() {}

func (x *Gift) ProtoReflect() protoreflect.Message {
	mi := &file_mqmarket_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gift.ProtoReflect.Descriptor instead.
func (*Gift) Descriptor() ([]byte, []int) {
	return file_mqmarket_api_proto_rawDescGZIP(), []int{0}
}

func (x *Gift) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *Gift) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Gift) GetUnits() int64 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *Gift) GetTimeFrame() Gift_TimeFrame {
	if x != nil {
		return x.TimeFrame
	}
	return Gift_UNKNOWN
}

var File_mqmarket_api_proto protoreflect.FileDescriptor

var file_mqmarket_api_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x71, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x71, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x22, 0xc4,
	0x01, 0x0a, 0x04, 0x47, 0x69, 0x66, 0x74, 0x12, 0x1c, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x75,
	0x6e, 0x69, 0x74, 0x73, 0x12, 0x37, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6d, 0x71, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x22, 0x36, 0x0a,
	0x09, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x41, 0x59, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x57, 0x45, 0x45, 0x4b, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x4f,
	0x4e, 0x54, 0x48, 0x10, 0x03, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mqmarket_api_proto_rawDescOnce sync.Once
	file_mqmarket_api_proto_rawDescData = file_mqmarket_api_proto_rawDesc
)

func file_mqmarket_api_proto_rawDescGZIP() []byte {
	file_mqmarket_api_proto_rawDescOnce.Do(func() {
		file_mqmarket_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_mqmarket_api_proto_rawDescData)
	})
	return file_mqmarket_api_proto_rawDescData
}

var file_mqmarket_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mqmarket_api_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mqmarket_api_proto_goTypes = []interface{}{
	(Gift_TimeFrame)(0), // 0: mqmarket.Gift.TimeFrame
	(*Gift)(nil),        // 1: mqmarket.Gift
}
var file_mqmarket_api_proto_depIdxs = []int32{
	0, // 0: mqmarket.Gift.time_frame:type_name -> mqmarket.Gift.TimeFrame
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mqmarket_api_proto_init() }
func file_mqmarket_api_proto_init() {
	if File_mqmarket_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mqmarket_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gift); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mqmarket_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mqmarket_api_proto_goTypes,
		DependencyIndexes: file_mqmarket_api_proto_depIdxs,
		EnumInfos:         file_mqmarket_api_proto_enumTypes,
		MessageInfos:      file_mqmarket_api_proto_msgTypes,
	}.Build()
	File_mqmarket_api_proto = out.File
	file_mqmarket_api_proto_rawDesc = nil
	file_mqmarket_api_proto_goTypes = nil
	file_mqmarket_api_proto_depIdxs = nil
}
