// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: mqmessenger/api.proto

package mqmessenger

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Message_Topology int32

const (
	Message_UNKNOWN   Message_Topology = 0
	Message_P2P       Message_Topology = 1
	Message_BROADCAST Message_Topology = 2
)

// Enum value maps for Message_Topology.
var (
	Message_Topology_name = map[int32]string{
		0: "UNKNOWN",
		1: "P2P",
		2: "BROADCAST",
	}
	Message_Topology_value = map[string]int32{
		"UNKNOWN":   0,
		"P2P":       1,
		"BROADCAST": 2,
	}
)

func (x Message_Topology) Enum() *Message_Topology {
	p := new(Message_Topology)
	*p = x
	return p
}

func (x Message_Topology) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Topology) Descriptor() protoreflect.EnumDescriptor {
	return file_mqmessenger_api_proto_enumTypes[0].Descriptor()
}

func (Message_Topology) Type() protoreflect.EnumType {
	return &file_mqmessenger_api_proto_enumTypes[0]
}

func (x Message_Topology) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Topology.Descriptor instead.
func (Message_Topology) EnumDescriptor() ([]byte, []int) {
	return file_mqmessenger_api_proto_rawDescGZIP(), []int{0, 0}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToUserId   string           `protobuf:"bytes,1,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	FromUserId string           `protobuf:"bytes,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	Text     string           `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Topology Message_Topology `protobuf:"varint,4,opt,name=topology,proto3,enum=mqmessenger.Message_Topology" json:"topology,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqmessenger_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_mqmessenger_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_mqmessenger_api_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *Message) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetTopology() Message_Topology {
	if x != nil {
		return x.Topology
	}
	return Message_UNKNOWN
}

var File_mqmessenger_api_proto protoreflect.FileDescriptor

var file_mqmessenger_api_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x71, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2f, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x71, 0x6d, 0x65, 0x73, 0x73, 0x65,
	0x6e, 0x67, 0x65, 0x72, 0x22, 0xc9, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1c, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x39, 0x0a, 0x08, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6d, 0x71, 0x6d, 0x65, 0x73, 0x73, 0x65,
	0x6e, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x6f, 0x70,
	0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x08, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x22,
	0x2f, 0x0a, 0x08, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x32, 0x50, 0x10,
	0x01, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x52, 0x4f, 0x41, 0x44, 0x43, 0x41, 0x53, 0x54, 0x10, 0x02,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mqmessenger_api_proto_rawDescOnce sync.Once
	file_mqmessenger_api_proto_rawDescData = file_mqmessenger_api_proto_rawDesc
)

func file_mqmessenger_api_proto_rawDescGZIP() []byte {
	file_mqmessenger_api_proto_rawDescOnce.Do(func() {
		file_mqmessenger_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_mqmessenger_api_proto_rawDescData)
	})
	return file_mqmessenger_api_proto_rawDescData
}

var file_mqmessenger_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mqmessenger_api_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mqmessenger_api_proto_goTypes = []interface{}{
	(Message_Topology)(0), // 0: mqmessenger.Message.Topology
	(*Message)(nil),       // 1: mqmessenger.Message
}
var file_mqmessenger_api_proto_depIdxs = []int32{
	0, // 0: mqmessenger.Message.topology:type_name -> mqmessenger.Message.Topology
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mqmessenger_api_proto_init() }
func file_mqmessenger_api_proto_init() {
	if File_mqmessenger_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mqmessenger_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mqmessenger_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mqmessenger_api_proto_goTypes,
		DependencyIndexes: file_mqmessenger_api_proto_depIdxs,
		EnumInfos:         file_mqmessenger_api_proto_enumTypes,
		MessageInfos:      file_mqmessenger_api_proto_msgTypes,
	}.Build()
	File_mqmessenger_api_proto = out.File
	file_mqmessenger_api_proto_rawDesc = nil
	file_mqmessenger_api_proto_goTypes = nil
	file_mqmessenger_api_proto_depIdxs = nil
}
