// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: grpctable/api.proto

package grpctable

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetTableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId string `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
}

func (x *GetTableRequest) Reset() {
	*x = GetTableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpctable_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableRequest) ProtoMessage() {}

func (x *GetTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpctable_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableRequest.ProtoReflect.Descriptor instead.
func (*GetTableRequest) Descriptor() ([]byte, []int) {
	return file_grpctable_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetTableRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type GetTableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableJson []byte `protobuf:"bytes,1,opt,name=table_json,json=tableJson,proto3" json:"table_json,omitempty"`
}

func (x *GetTableResponse) Reset() {
	*x = GetTableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpctable_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableResponse) ProtoMessage() {}

func (x *GetTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpctable_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableResponse.ProtoReflect.Descriptor instead.
func (*GetTableResponse) Descriptor() ([]byte, []int) {
	return file_grpctable_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetTableResponse) GetTableJson() []byte {
	if x != nil {
		return x.TableJson
	}
	return nil
}

type CreateSurvivalTableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                 string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BigBlind             int64  `protobuf:"varint,2,opt,name=big_blind,json=bigBlind,proto3" json:"big_blind,omitempty"`
	DecisionTimeSec      int64  `protobuf:"varint,3,opt,name=decision_time_sec,json=decisionTimeSec,proto3" json:"decision_time_sec,omitempty"`
	LevelIncreaseTimeSec int64  `protobuf:"varint,7,opt,name=level_increase_time_sec,json=levelIncreaseTimeSec,proto3" json:"level_increase_time_sec,omitempty"`
	ThemeId              string `protobuf:"bytes,4,opt,name=theme_id,json=themeId,proto3" json:"theme_id,omitempty"`
	User                 *User  `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Bots                 []*Bot `protobuf:"bytes,6,rep,name=bots,proto3" json:"bots,omitempty"`
	SurvivalLevel        int64  `protobuf:"varint,8,opt,name=survival_level,json=survivalLevel,proto3" json:"survival_level,omitempty"`
}

func (x *CreateSurvivalTableRequest) Reset() {
	*x = CreateSurvivalTableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpctable_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSurvivalTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSurvivalTableRequest) ProtoMessage() {}

func (x *CreateSurvivalTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpctable_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSurvivalTableRequest.ProtoReflect.Descriptor instead.
func (*CreateSurvivalTableRequest) Descriptor() ([]byte, []int) {
	return file_grpctable_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSurvivalTableRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSurvivalTableRequest) GetBigBlind() int64 {
	if x != nil {
		return x.BigBlind
	}
	return 0
}

func (x *CreateSurvivalTableRequest) GetDecisionTimeSec() int64 {
	if x != nil {
		return x.DecisionTimeSec
	}
	return 0
}

func (x *CreateSurvivalTableRequest) GetLevelIncreaseTimeSec() int64 {
	if x != nil {
		return x.LevelIncreaseTimeSec
	}
	return 0
}

func (x *CreateSurvivalTableRequest) GetThemeId() string {
	if x != nil {
		return x.ThemeId
	}
	return ""
}

func (x *CreateSurvivalTableRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateSurvivalTableRequest) GetBots() []*Bot {
	if x != nil {
		return x.Bots
	}
	return nil
}

func (x *CreateSurvivalTableRequest) GetSurvivalLevel() int64 {
	if x != nil {
		return x.SurvivalLevel
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Picture  string `protobuf:"bytes,3,opt,name=picture,proto3" json:"picture,omitempty"`
	Stack    int64  `protobuf:"varint,4,opt,name=stack,proto3" json:"stack,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpctable_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_grpctable_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_grpctable_api_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *User) GetStack() int64 {
	if x != nil {
		return x.Stack
	}
	return 0
}

type Bot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Picture string `protobuf:"bytes,2,opt,name=picture,proto3" json:"picture,omitempty"`
	Stack   int64  `protobuf:"varint,3,opt,name=stack,proto3" json:"stack,omitempty"`
}

func (x *Bot) Reset() {
	*x = Bot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpctable_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bot) ProtoMessage() {}

func (x *Bot) ProtoReflect() protoreflect.Message {
	mi := &file_grpctable_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bot.ProtoReflect.Descriptor instead.
func (*Bot) Descriptor() ([]byte, []int) {
	return file_grpctable_api_proto_rawDescGZIP(), []int{4}
}

func (x *Bot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bot) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *Bot) GetStack() int64 {
	if x != nil {
		return x.Stack
	}
	return 0
}

type CreateSurvivalTableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableJson []byte `protobuf:"bytes,1,opt,name=table_json,json=tableJson,proto3" json:"table_json,omitempty"`
}

func (x *CreateSurvivalTableResponse) Reset() {
	*x = CreateSurvivalTableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpctable_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSurvivalTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSurvivalTableResponse) ProtoMessage() {}

func (x *CreateSurvivalTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpctable_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSurvivalTableResponse.ProtoReflect.Descriptor instead.
func (*CreateSurvivalTableResponse) Descriptor() ([]byte, []int) {
	return file_grpctable_api_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSurvivalTableResponse) GetTableJson() []byte {
	if x != nil {
		return x.TableJson
	}
	return nil
}

type DeleteSurvivalTableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId string `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
}

func (x *DeleteSurvivalTableRequest) Reset() {
	*x = DeleteSurvivalTableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpctable_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSurvivalTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSurvivalTableRequest) ProtoMessage() {}

func (x *DeleteSurvivalTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpctable_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSurvivalTableRequest.ProtoReflect.Descriptor instead.
func (*DeleteSurvivalTableRequest) Descriptor() ([]byte, []int) {
	return file_grpctable_api_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSurvivalTableRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type MakeActionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId    string `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Position   int64  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	ActionType string `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Chips      int64  `protobuf:"varint,4,opt,name=chips,proto3" json:"chips,omitempty"`
}

func (x *MakeActionRequest) Reset() {
	*x = MakeActionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpctable_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeActionRequest) ProtoMessage() {}

func (x *MakeActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpctable_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeActionRequest.ProtoReflect.Descriptor instead.
func (*MakeActionRequest) Descriptor() ([]byte, []int) {
	return file_grpctable_api_proto_rawDescGZIP(), []int{7}
}

func (x *MakeActionRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *MakeActionRequest) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *MakeActionRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *MakeActionRequest) GetChips() int64 {
	if x != nil {
		return x.Chips
	}
	return 0
}

type SitBackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position int64  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	TableId  string `protobuf:"bytes,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
}

func (x *SitBackRequest) Reset() {
	*x = SitBackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpctable_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SitBackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SitBackRequest) ProtoMessage() {}

func (x *SitBackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpctable_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SitBackRequest.ProtoReflect.Descriptor instead.
func (*SitBackRequest) Descriptor() ([]byte, []int) {
	return file_grpctable_api_proto_rawDescGZIP(), []int{8}
}

func (x *SitBackRequest) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *SitBackRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

var File_grpctable_api_proto protoreflect.FileDescriptor

var file_grpctable_api_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x72, 0x70, 0x63, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x72, 0x70, 0x63, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0xbb,
	0x02, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x72, 0x76, 0x69, 0x76, 0x61,
	0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x69, 0x67, 0x5f, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x69, 0x67, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x12, 0x2a,
	0x0a, 0x11, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x73, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x64, 0x65, 0x63, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x12, 0x35, 0x0a, 0x17, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x5f, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x14, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x65,
	0x63, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x12, 0x22, 0x0a, 0x04, 0x62, 0x6f, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x42, 0x6f, 0x74, 0x52,
	0x04, 0x62, 0x6f, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x75, 0x72, 0x76, 0x69, 0x76, 0x61,
	0x6c, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x73,
	0x75, 0x72, 0x76, 0x69, 0x76, 0x61, 0x6c, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x6b, 0x0a, 0x04,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x22, 0x49, 0x0a, 0x03, 0x42, 0x6f, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x63, 0x6b, 0x22, 0x3c, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75,
	0x72, 0x76, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6a, 0x73, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4a, 0x73,
	0x6f, 0x6e, 0x22, 0x37, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x75, 0x72, 0x76,
	0x69, 0x76, 0x61, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x11,
	0x4d, 0x61, 0x6b, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x69,
	0x70, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x68, 0x69, 0x70, 0x73, 0x22,
	0x47, 0x0a, 0x0e, 0x53, 0x69, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a,
	0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x32, 0x9b, 0x03, 0x0a, 0x0c, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x66, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x72, 0x76, 0x69, 0x76,
	0x61, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x25, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x72, 0x76, 0x69, 0x76,
	0x61, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x75, 0x72, 0x76, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x53, 0x75, 0x72, 0x76, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x25, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x53, 0x75, 0x72, 0x76, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x44, 0x0a, 0x0a, 0x4d, 0x61, 0x6b, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x07, 0x53, 0x69, 0x74, 0x42, 0x61, 0x63,
	0x6b, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x53, 0x69,
	0x74, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpctable_api_proto_rawDescOnce sync.Once
	file_grpctable_api_proto_rawDescData = file_grpctable_api_proto_rawDesc
)

func file_grpctable_api_proto_rawDescGZIP() []byte {
	file_grpctable_api_proto_rawDescOnce.Do(func() {
		file_grpctable_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpctable_api_proto_rawDescData)
	})
	return file_grpctable_api_proto_rawDescData
}

var file_grpctable_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_grpctable_api_proto_goTypes = []interface{}{
	(*GetTableRequest)(nil),             // 0: grpctable.GetTableRequest
	(*GetTableResponse)(nil),            // 1: grpctable.GetTableResponse
	(*CreateSurvivalTableRequest)(nil),  // 2: grpctable.CreateSurvivalTableRequest
	(*User)(nil),                        // 3: grpctable.User
	(*Bot)(nil),                         // 4: grpctable.Bot
	(*CreateSurvivalTableResponse)(nil), // 5: grpctable.CreateSurvivalTableResponse
	(*DeleteSurvivalTableRequest)(nil),  // 6: grpctable.DeleteSurvivalTableRequest
	(*MakeActionRequest)(nil),           // 7: grpctable.MakeActionRequest
	(*SitBackRequest)(nil),              // 8: grpctable.SitBackRequest
	(*empty.Empty)(nil),                 // 9: google.protobuf.Empty
}
var file_grpctable_api_proto_depIdxs = []int32{
	3, // 0: grpctable.CreateSurvivalTableRequest.user:type_name -> grpctable.User
	4, // 1: grpctable.CreateSurvivalTableRequest.bots:type_name -> grpctable.Bot
	0, // 2: grpctable.TableService.GetTable:input_type -> grpctable.GetTableRequest
	2, // 3: grpctable.TableService.CreateSurvivalTable:input_type -> grpctable.CreateSurvivalTableRequest
	6, // 4: grpctable.TableService.DeleteSurvivalTable:input_type -> grpctable.DeleteSurvivalTableRequest
	7, // 5: grpctable.TableService.MakeAction:input_type -> grpctable.MakeActionRequest
	8, // 6: grpctable.TableService.SitBack:input_type -> grpctable.SitBackRequest
	1, // 7: grpctable.TableService.GetTable:output_type -> grpctable.GetTableResponse
	5, // 8: grpctable.TableService.CreateSurvivalTable:output_type -> grpctable.CreateSurvivalTableResponse
	9, // 9: grpctable.TableService.DeleteSurvivalTable:output_type -> google.protobuf.Empty
	9, // 10: grpctable.TableService.MakeAction:output_type -> google.protobuf.Empty
	9, // 11: grpctable.TableService.SitBack:output_type -> google.protobuf.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpctable_api_proto_init() }
func file_grpctable_api_proto_init() {
	if File_grpctable_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpctable_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpctable_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpctable_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSurvivalTableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpctable_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpctable_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpctable_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSurvivalTableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpctable_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSurvivalTableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpctable_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeActionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpctable_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SitBackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpctable_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpctable_api_proto_goTypes,
		DependencyIndexes: file_grpctable_api_proto_depIdxs,
		MessageInfos:      file_grpctable_api_proto_msgTypes,
	}.Build()
	File_grpctable_api_proto = out.File
	file_grpctable_api_proto_rawDesc = nil
	file_grpctable_api_proto_goTypes = nil
	file_grpctable_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TableServiceClient is the client API for TableService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TableServiceClient interface {
	GetTable(ctx context.Context, in *GetTableRequest, opts ...grpc.CallOption) (*GetTableResponse, error)
	CreateSurvivalTable(ctx context.Context, in *CreateSurvivalTableRequest, opts ...grpc.CallOption) (*CreateSurvivalTableResponse, error)
	DeleteSurvivalTable(ctx context.Context, in *DeleteSurvivalTableRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	MakeAction(ctx context.Context, in *MakeActionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	SitBack(ctx context.Context, in *SitBackRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type tableServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTableServiceClient(cc grpc.ClientConnInterface) TableServiceClient {
	return &tableServiceClient{cc}
}

func (c *tableServiceClient) GetTable(ctx context.Context, in *GetTableRequest, opts ...grpc.CallOption) (*GetTableResponse, error) {
	out := new(GetTableResponse)
	err := c.cc.Invoke(ctx, "/grpctable.TableService/GetTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) CreateSurvivalTable(ctx context.Context, in *CreateSurvivalTableRequest, opts ...grpc.CallOption) (*CreateSurvivalTableResponse, error) {
	out := new(CreateSurvivalTableResponse)
	err := c.cc.Invoke(ctx, "/grpctable.TableService/CreateSurvivalTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) DeleteSurvivalTable(ctx context.Context, in *DeleteSurvivalTableRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpctable.TableService/DeleteSurvivalTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) MakeAction(ctx context.Context, in *MakeActionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpctable.TableService/MakeAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) SitBack(ctx context.Context, in *SitBackRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpctable.TableService/SitBack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TableServiceServer is the server API for TableService service.
type TableServiceServer interface {
	GetTable(context.Context, *GetTableRequest) (*GetTableResponse, error)
	CreateSurvivalTable(context.Context, *CreateSurvivalTableRequest) (*CreateSurvivalTableResponse, error)
	DeleteSurvivalTable(context.Context, *DeleteSurvivalTableRequest) (*empty.Empty, error)
	MakeAction(context.Context, *MakeActionRequest) (*empty.Empty, error)
	SitBack(context.Context, *SitBackRequest) (*empty.Empty, error)
}

// UnimplementedTableServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTableServiceServer struct {
}

func (*UnimplementedTableServiceServer) GetTable(context.Context, *GetTableRequest) (*GetTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTable not implemented")
}
func (*UnimplementedTableServiceServer) CreateSurvivalTable(context.Context, *CreateSurvivalTableRequest) (*CreateSurvivalTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSurvivalTable not implemented")
}
func (*UnimplementedTableServiceServer) DeleteSurvivalTable(context.Context, *DeleteSurvivalTableRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSurvivalTable not implemented")
}
func (*UnimplementedTableServiceServer) MakeAction(context.Context, *MakeActionRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeAction not implemented")
}
func (*UnimplementedTableServiceServer) SitBack(context.Context, *SitBackRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SitBack not implemented")
}

func RegisterTableServiceServer(s *grpc.Server, srv TableServiceServer) {
	s.RegisterService(&_TableService_serviceDesc, srv)
}

func _TableService_GetTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).GetTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctable.TableService/GetTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).GetTable(ctx, req.(*GetTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_CreateSurvivalTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSurvivalTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).CreateSurvivalTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctable.TableService/CreateSurvivalTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).CreateSurvivalTable(ctx, req.(*CreateSurvivalTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_DeleteSurvivalTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSurvivalTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).DeleteSurvivalTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctable.TableService/DeleteSurvivalTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).DeleteSurvivalTable(ctx, req.(*DeleteSurvivalTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_MakeAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).MakeAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctable.TableService/MakeAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).MakeAction(ctx, req.(*MakeActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_SitBack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SitBackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).SitBack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctable.TableService/SitBack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).SitBack(ctx, req.(*SitBackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TableService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpctable.TableService",
	HandlerType: (*TableServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTable",
			Handler:    _TableService_GetTable_Handler,
		},
		{
			MethodName: "CreateSurvivalTable",
			Handler:    _TableService_CreateSurvivalTable_Handler,
		},
		{
			MethodName: "DeleteSurvivalTable",
			Handler:    _TableService_DeleteSurvivalTable_Handler,
		},
		{
			MethodName: "MakeAction",
			Handler:    _TableService_MakeAction_Handler,
		},
		{
			MethodName: "SitBack",
			Handler:    _TableService_SitBack_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpctable/api.proto",
}
